# Generated by Django 5.1.3 on 2024-11-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='Lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_materials.course', verbose_name='Course'),
        ),
    ]
