# Generated by Django 5.1.3 on 2025-06-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0004_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_link',
            new_name='video_url',
        ),
    ]
